language: php
sudo: false
dist: trusty
php:
- 7.1
- 7.0
- 5.6
- nightly
env:
- TRAVIS_NODE_VERSION="6"
- TRAVIS_NODE_VERSION="7"
matrix:
  fast_finish: true
  allow_failures:
  - php: nightly
cache:
  apt: true
  directories:
  - $HOME/.composer/cache
  - vendor
before_install:
- composer self-update
  | bash
install:
- composer install -o --prefer-dist --no-interaction
script:
- composer test
notifications:
  slack: wildfirepublicity:Lw0t3aIPsbkmGhdO6TLc9wOA
